[package]
name = "almost"
version = "0.0.1"
authors = ["Thom Chiovoloni <chiovolonit@gmail.com>"]
edition = "2018"
license = "CC0-1.0"
description = "almost"

[dependencies]

[dev-dependencies]
ieee754 = "0.2.6"
rand = { version = "0.6.5", default-features = false }

