version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - Run tests
  cross:
    jobs:
      - Cross Test

jobs:
  Run tests:
    docker:
      - image: circleci/rust:1.35.0

    steps:
      - checkout

      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Test native
          command: cargo test --all --verbose

  Cross Test:
    machine: true
    steps:
      - checkout
      - run:
          name: Download rustup
          command: |
            wget https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
            chmod +x rustup-init
      - run:
          name: Install Rust
          command: |
            ./rustup-init -y --no-modify-path
            rm rustup-init
            echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $BASH_ENV

      - run: rustup target add i686-unknown-linux-gnu mipsel-unknown-linux-gnu armv7-unknown-linux-gnueabihf

      - run: cargo install cross

      - run:
          name: Test i686
          command: cross test --target=i686-unknown-linux-gnu
      - run:
          name: Test mipsel
          command: cross test --target=mipsel-unknown-linux-gnu
      - run:
          name: Test arm
          command: cross test --target=armv7-unknown-linux-gnueabihf
